[package]
name = "my-observability-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = "0.12"
aya-log = "0.2"
my-observability-tool-common = { path = "../my-observability-tool-common" }
tokio = { version = "1.35", features = ["full", "signal"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
bytes = "1.5"
